import state from '../state.js';
import { hexColor } from '../utils.js';

export function drawRobot(ctx, e) {
  let cx = e.x, cy = e.y;
  let s = e.type.size;
  let col = e.type.color;
  let name = e.type.name;
  let walk = e.walkCycle;
  let facing = e.facing;
  let slowed = e.slowTimer > 0;

  ctx.save();
  ctx.translate(cx, cy);

  if (name === 'Scout') {
    let legSwing = Math.sin(walk) * 0.4;
    let bodyBob = Math.abs(Math.sin(walk)) * 1.5;
    ctx.strokeStyle = '#888';
    ctx.lineWidth = 2;
    ctx.save();
    ctx.beginPath();
    ctx.moveTo(-3, 2 - bodyBob);
    ctx.lineTo(-5, 7 + Math.sin(walk)*2);
    ctx.lineTo(-3, 10);
    ctx.stroke();
    ctx.restore();
    ctx.beginPath();
    ctx.moveTo(3, 2 - bodyBob);
    ctx.lineTo(5, 7 + Math.sin(walk + Math.PI)*2);
    ctx.lineTo(3, 10);
    ctx.stroke();
    ctx.fillStyle = '#666';
    ctx.fillRect(-5, 9 + Math.sin(walk)*2, 4, 2);
    ctx.fillRect(2, 9 + Math.sin(walk+Math.PI)*2, 4, 2);
    ctx.fillStyle = '#922';
    ctx.beginPath();
    ctx.moveTo(-5, -3 - bodyBob);
    ctx.lineTo(5, -3 - bodyBob);
    ctx.lineTo(6, 3 - bodyBob);
    ctx.lineTo(-6, 3 - bodyBob);
    ctx.closePath();
    ctx.fill();
    ctx.strokeStyle = '#c44';
    ctx.lineWidth = 0.8;
    ctx.stroke();
    ctx.fillStyle = '#a33';
    ctx.fillRect(-4, -7 - bodyBob, 8, 4);
    ctx.fillStyle = slowed ? '#ff0' : '#f00';
    ctx.fillRect(-3, -6 - bodyBob, 6, 2);
    ctx.shadowColor = slowed ? '#ff0' : '#f00';
    ctx.shadowBlur = 4;
    ctx.fillRect(-3, -6 - bodyBob, 6, 2);
    ctx.shadowBlur = 0;
    ctx.strokeStyle = '#888';
    ctx.lineWidth = 1;
    ctx.beginPath(); ctx.moveTo(0, -7 - bodyBob); ctx.lineTo(0, -11 - bodyBob); ctx.stroke();
    ctx.fillStyle = '#f00';
    ctx.beginPath(); ctx.arc(0, -11 - bodyBob, 1, 0, Math.PI*2); ctx.fill();

  } else if (name === 'Soldier') {
    let legSwing = Math.sin(walk) * 0.5;
    let bodyBob = Math.abs(Math.sin(walk)) * 1;
    ctx.fillStyle = '#885500';
    ctx.save();
    ctx.translate(-4, 3 - bodyBob);
    ctx.rotate(legSwing);
    ctx.fillRect(-2, 0, 4, 8);
    ctx.fillStyle = '#664400';
    ctx.fillRect(-2.5, 7, 5, 3);
    ctx.restore();
    ctx.save();
    ctx.translate(4, 3 - bodyBob);
    ctx.rotate(-legSwing);
    ctx.fillRect(-2, 0, 4, 8);
    ctx.fillStyle = '#664400';
    ctx.fillRect(-2.5, 7, 5, 3);
    ctx.restore();
    ctx.fillStyle = '#996600';
    ctx.beginPath();
    ctx.moveTo(-7, -4 - bodyBob); ctx.lineTo(7, -4 - bodyBob);
    ctx.lineTo(6, 4 - bodyBob); ctx.lineTo(-6, 4 - bodyBob);
    ctx.closePath();
    ctx.fill();
    ctx.strokeStyle = '#bb8800';
    ctx.lineWidth = 1;
    ctx.stroke();
    ctx.fillStyle = '#774400';
    ctx.fillRect(-4, -2 - bodyBob, 8, 3);
    ctx.strokeStyle = '#aa7700';
    ctx.strokeRect(-4, -2 - bodyBob, 8, 3);
    ctx.fillStyle = '#885500';
    ctx.fillRect(-10, -3 - bodyBob, 4, 6);
    ctx.fillRect(6, -3 - bodyBob, 4, 6);
    ctx.fillStyle = '#555';
    ctx.fillRect(9, -2 - bodyBob, 5, 2);
    ctx.fillStyle = '#885500';
    ctx.fillRect(-5, -9 - bodyBob, 10, 5);
    ctx.fillStyle = '#663300';
    ctx.fillRect(-4, -8 - bodyBob, 8, 3);
    ctx.fillStyle = slowed ? '#ff0' : '#fa0';
    ctx.shadowColor = slowed ? '#ff0' : '#fa0';
    ctx.shadowBlur = 4;
    ctx.fillRect(-3, -7 - bodyBob, 2, 1.5);
    ctx.fillRect(1, -7 - bodyBob, 2, 1.5);
    ctx.shadowBlur = 0;
    ctx.fillStyle = '#aa7700';
    ctx.beginPath(); ctx.arc(-8, -4 - bodyBob, 3, 0, Math.PI*2); ctx.fill();
    ctx.beginPath(); ctx.arc(8, -4 - bodyBob, 3, 0, Math.PI*2); ctx.fill();

  } else if (name === 'Tank') {
    let rumble = Math.sin(state.gameTime * 0.3) * 0.5;
    ctx.fillStyle = '#444';
    ctx.fillRect(-13, 4, 26, 6);
    ctx.fillStyle = '#333';
    for (let i = 0; i < 7; i++) {
      ctx.fillRect(-12 + i*4, 4.5, 2, 5);
    }
    ctx.strokeStyle = '#555';
    ctx.lineWidth = 1;
    ctx.strokeRect(-13, 4, 26, 6);
    ctx.fillStyle = '#555';
    ctx.beginPath(); ctx.arc(-10, 7, 2.5, 0, Math.PI*2); ctx.fill();
    ctx.beginPath(); ctx.arc(10, 7, 2.5, 0, Math.PI*2); ctx.fill();
    ctx.beginPath(); ctx.arc(0, 7, 2, 0, Math.PI*2); ctx.fill();
    ctx.fillStyle = '#733';
    ctx.beginPath();
    ctx.moveTo(-12, 4); ctx.lineTo(-10, -3 + rumble);
    ctx.lineTo(10, -3 + rumble); ctx.lineTo(12, 4);
    ctx.closePath();
    ctx.fill();
    ctx.strokeStyle = '#944';
    ctx.lineWidth = 1;
    ctx.stroke();
    ctx.fillStyle = '#622';
    ctx.fillRect(-8, -1 + rumble, 16, 3);
    ctx.save();
    ctx.translate(0, -4 + rumble);
    ctx.rotate(facing);
    ctx.fillStyle = '#844';
    ctx.beginPath();
    ctx.arc(0, 0, 6, 0, Math.PI*2);
    ctx.fill();
    ctx.strokeStyle = '#a66';
    ctx.stroke();
    ctx.fillStyle = '#655';
    ctx.fillRect(4, -2, 10, 4);
    ctx.fillStyle = '#533';
    ctx.fillRect(12, -2.5, 3, 5);
    ctx.restore();
    ctx.fillStyle = '#955';
    ctx.fillRect(-11, 0 + rumble, 3, 3);
    ctx.fillRect(8, 0 + rumble, 3, 3);
    ctx.fillStyle = slowed ? '#ff0' : '#f00';
    ctx.shadowColor = slowed ? '#ff0' : '#f00';
    ctx.shadowBlur = 3;
    ctx.beginPath(); ctx.arc(0, -5 + rumble, 1.5, 0, Math.PI*2); ctx.fill();
    ctx.shadowBlur = 0;

  } else if (name === 'Drone') {
    let hover = Math.sin(state.gameTime * 0.15) * 3;
    let propSpin = state.gameTime * 0.8;
    ctx.translate(0, hover);
    ctx.fillStyle = 'rgba(0,0,0,0.2)';
    ctx.beginPath();
    ctx.ellipse(0, 8 - hover, 6, 2, 0, 0, Math.PI*2);
    ctx.fill();
    ctx.strokeStyle = '#336';
    ctx.lineWidth = 2;
    ctx.beginPath(); ctx.moveTo(-8, -2); ctx.lineTo(8, -2); ctx.stroke();
    ctx.beginPath(); ctx.moveTo(-2, -6); ctx.lineTo(-2, 2); ctx.stroke();
    ctx.beginPath(); ctx.moveTo(2, -6); ctx.lineTo(2, 2); ctx.stroke();
    ctx.fillStyle = '#336';
    ctx.beginPath();
    ctx.moveTo(-3, -4); ctx.lineTo(3, -4);
    ctx.lineTo(4, 0); ctx.lineTo(3, 2);
    ctx.lineTo(-3, 2); ctx.lineTo(-4, 0);
    ctx.closePath();
    ctx.fill();
    ctx.strokeStyle = '#55a';
    ctx.lineWidth = 0.8;
    ctx.stroke();
    ctx.strokeStyle = hexColor('#4af', 0.6);
    ctx.lineWidth = 1.5;
    [[-8,-2],[8,-2],[-2,-6],[2,2]].forEach(([px,py], i) => {
      let a = propSpin + i * Math.PI/2;
      ctx.beginPath();
      ctx.moveTo(px + Math.cos(a)*4, py + Math.sin(a)*1.5);
      ctx.lineTo(px - Math.cos(a)*4, py - Math.sin(a)*1.5);
      ctx.stroke();
      ctx.strokeStyle = hexColor('#4af', 0.15);
      ctx.beginPath(); ctx.arc(px, py, 4, 0, Math.PI*2); ctx.stroke();
      ctx.strokeStyle = hexColor('#4af', 0.6);
    });
    ctx.fillStyle = slowed ? '#ff0' : '#4af';
    ctx.shadowColor = slowed ? '#ff0' : '#4af';
    ctx.shadowBlur = 6;
    ctx.beginPath(); ctx.arc(0, -1, 2, 0, Math.PI*2); ctx.fill();
    ctx.shadowBlur = 0;
    ctx.fillStyle = '#112';
    ctx.beginPath(); ctx.arc(0, -1, 1, 0, Math.PI*2); ctx.fill();

  } else if (name === 'Mech') {
    let legSwing = Math.sin(walk) * 0.3;
    let bodyBob = Math.abs(Math.sin(walk)) * 2;
    ctx.lineWidth = 3;
    ctx.save();
    ctx.translate(-6, 4 - bodyBob);
    ctx.rotate(legSwing);
    ctx.fillStyle = '#636';
    ctx.fillRect(-3, 0, 6, 8);
    ctx.fillStyle = '#858';
    ctx.beginPath(); ctx.arc(0, 8, 3, 0, Math.PI*2); ctx.fill();
    ctx.fillStyle = '#525';
    ctx.fillRect(-3, 8, 6, 8);
    ctx.fillStyle = '#747';
    ctx.beginPath();
    ctx.moveTo(-5, 16); ctx.lineTo(5, 16); ctx.lineTo(6, 18); ctx.lineTo(-6, 18);
    ctx.closePath();
    ctx.fill();
    ctx.restore();
    ctx.save();
    ctx.translate(6, 4 - bodyBob);
    ctx.rotate(-legSwing);
    ctx.fillStyle = '#636';
    ctx.fillRect(-3, 0, 6, 8);
    ctx.fillStyle = '#858';
    ctx.beginPath(); ctx.arc(0, 8, 3, 0, Math.PI*2); ctx.fill();
    ctx.fillStyle = '#525';
    ctx.fillRect(-3, 8, 6, 8);
    ctx.fillStyle = '#747';
    ctx.beginPath();
    ctx.moveTo(-5, 16); ctx.lineTo(5, 16); ctx.lineTo(6, 18); ctx.lineTo(-6, 18);
    ctx.closePath();
    ctx.fill();
    ctx.restore();
    ctx.fillStyle = '#747';
    ctx.beginPath();
    ctx.moveTo(-10, -6 - bodyBob); ctx.lineTo(10, -6 - bodyBob);
    ctx.lineTo(9, 5 - bodyBob); ctx.lineTo(-9, 5 - bodyBob);
    ctx.closePath();
    ctx.fill();
    ctx.strokeStyle = '#969';
    ctx.lineWidth = 1.5;
    ctx.stroke();
    ctx.fillStyle = hexColor('#f4f', 0.5 + Math.sin(state.gameTime*0.08)*0.3);
    ctx.beginPath(); ctx.arc(0, -1 - bodyBob, 4, 0, Math.PI*2); ctx.fill();
    ctx.strokeStyle = '#c3c';
    ctx.lineWidth = 1;
    ctx.stroke();
    ctx.fillStyle = '#fff';
    ctx.beginPath(); ctx.arc(0, -1 - bodyBob, 1.5, 0, Math.PI*2); ctx.fill();
    ctx.fillStyle = '#636';
    ctx.fillRect(-14, -9 - bodyBob, 5, 6);
    ctx.fillStyle = '#444';
    for (let i = 0; i < 2; i++)
      for (let j = 0; j < 2; j++)
        ctx.fillRect(-13.5 + j*2.5, -8.5 + i*2.5 - bodyBob, 2, 2);
    ctx.fillStyle = '#636';
    ctx.fillRect(9, -9 - bodyBob, 5, 6);
    ctx.fillStyle = '#555';
    ctx.fillRect(13, -8 - bodyBob, 6, 1.5);
    ctx.fillRect(13, -6 - bodyBob, 6, 1.5);
    ctx.fillStyle = '#858';
    ctx.beginPath();
    ctx.moveTo(-5, -10 - bodyBob); ctx.lineTo(5, -10 - bodyBob);
    ctx.lineTo(4, -6 - bodyBob); ctx.lineTo(-4, -6 - bodyBob);
    ctx.closePath();
    ctx.fill();
    ctx.fillStyle = slowed ? '#ff0' : '#f4f';
    ctx.shadowColor = slowed ? '#ff0' : '#f4f';
    ctx.shadowBlur = 6;
    ctx.fillRect(-4, -9 - bodyBob, 8, 2);
    ctx.shadowBlur = 0;
    ctx.strokeStyle = '#888';
    ctx.lineWidth = 1;
    ctx.beginPath(); ctx.moveTo(-2, -10 - bodyBob); ctx.lineTo(-3, -14 - bodyBob); ctx.stroke();
    ctx.beginPath(); ctx.moveTo(2, -10 - bodyBob); ctx.lineTo(3, -14 - bodyBob); ctx.stroke();

  } else if (name === 'Swarm') {
    let scurry = walk * 2;
    ctx.strokeStyle = '#484';
    ctx.lineWidth = 1;
    for (let i = 0; i < 6; i++) {
      let angle = (i / 6) * Math.PI * 2 + Math.sin(scurry + i * 1.2) * 0.3;
      let legLen = 5 + Math.sin(scurry + i * 1.5) * 1;
      ctx.beginPath();
      ctx.moveTo(Math.cos(angle) * 2, Math.sin(angle) * 2);
      let midX = Math.cos(angle) * 4;
      let midY = Math.sin(angle) * 4 - 2;
      ctx.lineTo(midX, midY);
      ctx.lineTo(Math.cos(angle) * legLen, Math.sin(angle) * legLen + 1);
      ctx.stroke();
    }
    ctx.fillStyle = '#4a4';
    ctx.beginPath();
    ctx.ellipse(0, 0, 4, 3, 0, 0, Math.PI * 2);
    ctx.fill();
    ctx.strokeStyle = '#6c6';
    ctx.lineWidth = 0.5;
    ctx.stroke();
    ctx.fillStyle = '#383';
    ctx.beginPath();
    ctx.ellipse(-2, 1, 2.5, 2, 0.3, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = slowed ? '#ff0' : '#f00';
    ctx.shadowColor = slowed ? '#ff0' : '#f00';
    ctx.shadowBlur = 3;
    ctx.beginPath(); ctx.arc(2, -1.5, 1, 0, Math.PI*2); ctx.fill();
    ctx.beginPath(); ctx.arc(3, 0, 0.8, 0, Math.PI*2); ctx.fill();
    ctx.beginPath(); ctx.arc(2, 1, 0.8, 0, Math.PI*2); ctx.fill();
    ctx.shadowBlur = 0;

  } else if (name === 'Titan') {
    let legSwing = Math.sin(walk) * 0.25;
    let bodyBob = Math.abs(Math.sin(walk)) * 2;
    let breathe = Math.sin(state.gameTime * 0.05) * 0.5;
    ctx.save();
    ctx.translate(-10, 6 - bodyBob);
    ctx.rotate(legSwing);
    ctx.fillStyle = '#888';
    ctx.fillRect(-3, 0, 6, 10);
    ctx.fillStyle = '#999';
    ctx.beginPath(); ctx.arc(0, 10, 3, 0, Math.PI*2); ctx.fill();
    ctx.fillRect(-3, 10, 6, 8);
    ctx.fillStyle = '#aaa';
    ctx.fillRect(-5, 17, 8, 3);
    ctx.restore();
    ctx.save();
    ctx.translate(10, 6 - bodyBob);
    ctx.rotate(-legSwing);
    ctx.fillStyle = '#888';
    ctx.fillRect(-3, 0, 6, 10);
    ctx.fillStyle = '#999';
    ctx.beginPath(); ctx.arc(0, 10, 3, 0, Math.PI*2); ctx.fill();
    ctx.fillRect(-3, 10, 6, 8);
    ctx.fillStyle = '#aaa';
    ctx.fillRect(-3, 17, 8, 3);
    ctx.restore();
    ctx.save();
    ctx.translate(-8, 2 - bodyBob);
    ctx.rotate(-legSwing);
    ctx.fillStyle = '#999';
    ctx.fillRect(-3, 0, 5, 10);
    ctx.fillStyle = '#aaa';
    ctx.beginPath(); ctx.arc(0, 10, 2.5, 0, Math.PI*2); ctx.fill();
    ctx.fillRect(-3, 10, 5, 7);
    ctx.fillStyle = '#bbb';
    ctx.fillRect(-4, 16, 7, 3);
    ctx.restore();
    ctx.save();
    ctx.translate(8, 2 - bodyBob);
    ctx.rotate(legSwing);
    ctx.fillStyle = '#999';
    ctx.fillRect(-2, 0, 5, 10);
    ctx.fillStyle = '#aaa';
    ctx.beginPath(); ctx.arc(0, 10, 2.5, 0, Math.PI*2); ctx.fill();
    ctx.fillRect(-2, 10, 5, 7);
    ctx.fillStyle = '#bbb';
    ctx.fillRect(-3, 16, 7, 3);
    ctx.restore();
    ctx.fillStyle = '#aaa';
    ctx.beginPath();
    ctx.moveTo(-14, -4 - bodyBob); ctx.lineTo(14, -4 - bodyBob);
    ctx.lineTo(13, 8 - bodyBob); ctx.lineTo(-13, 8 - bodyBob);
    ctx.closePath();
    ctx.fill();
    ctx.strokeStyle = '#ccc';
    ctx.lineWidth = 1.5;
    ctx.stroke();
    ctx.fillStyle = '#999';
    ctx.fillRect(-12, -2 - bodyBob, 24, 3);
    ctx.fillRect(-12, 3 - bodyBob, 24, 3);
    ctx.fillStyle = '#bbb';
    for (let i = 0; i < 6; i++) {
      ctx.beginPath(); ctx.arc(-10 + i*4, -2 - bodyBob, 1, 0, Math.PI*2); ctx.fill();
      ctx.beginPath(); ctx.arc(-10 + i*4, 6 - bodyBob, 1, 0, Math.PI*2); ctx.fill();
    }
    ctx.fillStyle = hexColor('#fff', 0.4 + breathe * 0.3);
    ctx.shadowColor = '#fff';
    ctx.shadowBlur = 10;
    ctx.beginPath(); ctx.arc(0, 1 - bodyBob, 5, 0, Math.PI*2); ctx.fill();
    ctx.shadowBlur = 0;
    ctx.strokeStyle = '#ddd';
    ctx.lineWidth = 1;
    ctx.stroke();
    ctx.fillStyle = '#fff';
    ctx.beginPath(); ctx.arc(0, 1 - bodyBob, 2, 0, Math.PI*2); ctx.fill();
    ctx.fillStyle = '#bbb';
    ctx.beginPath();
    ctx.moveTo(-8, -10 - bodyBob); ctx.lineTo(8, -10 - bodyBob);
    ctx.lineTo(10, -4 - bodyBob); ctx.lineTo(-10, -4 - bodyBob);
    ctx.closePath();
    ctx.fill();
    ctx.strokeStyle = '#ddd';
    ctx.stroke();
    ctx.fillStyle = slowed ? '#ff0' : '#f44';
    ctx.shadowColor = slowed ? '#ff0' : '#f44';
    ctx.shadowBlur = 8;
    ctx.fillRect(-7, -9 - bodyBob, 14, 3);
    ctx.shadowBlur = 0;
    ctx.fillStyle = '#200';
    ctx.fillRect(-3, -9 - bodyBob, 1, 3);
    ctx.fillRect(2, -9 - bodyBob, 1, 3);
    ctx.fillStyle = '#999';
    ctx.fillRect(-16, -8 - bodyBob, 5, 5);
    ctx.fillRect(11, -8 - bodyBob, 5, 5);
    ctx.fillStyle = '#777';
    ctx.fillRect(-17, -7 - bodyBob, 2, 3);
    ctx.fillRect(16, -7 - bodyBob, 2, 3);
    ctx.strokeStyle = '#ccc';
    ctx.lineWidth = 2;
    ctx.beginPath(); ctx.moveTo(-6, -10 - bodyBob); ctx.lineTo(-8, -16 - bodyBob); ctx.stroke();
    ctx.beginPath(); ctx.moveTo(6, -10 - bodyBob); ctx.lineTo(8, -16 - bodyBob); ctx.stroke();
    ctx.fillStyle = '#f00';
    ctx.beginPath(); ctx.arc(-8, -16 - bodyBob, 1.5, 0, Math.PI*2); ctx.fill();
    ctx.beginPath(); ctx.arc(8, -16 - bodyBob, 1.5, 0, Math.PI*2); ctx.fill();
  }

  ctx.restore();

  // HP bar
  let bw = Math.max(s * 2.5, 16);
  let bh = 3;
  let bx = cx - bw/2;
  let barOffset = name === 'Titan' ? 22 : name === 'Mech' ? 18 : name === 'Drone' ? 12 : s + 6;
  let by = cy - barOffset;
  ctx.fillStyle = '#300';
  ctx.fillRect(bx, by, bw, bh);
  let hpRatio = e.hp / e.maxHp;
  ctx.fillStyle = hpRatio > 0.5 ? '#0f0' : hpRatio > 0.25 ? '#ff0' : '#f00';
  ctx.fillRect(bx, by, bw * hpRatio, bh);
  ctx.strokeStyle = '#555';
  ctx.lineWidth = 0.5;
  ctx.strokeRect(bx, by, bw, bh);
}
